insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('UR164', 'sed', 'ut at', 'Gastronomía y Gestión Culinaria', 3);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('ML169', 'sed', 'pretium quis lectus', 'Diseño y Gestión en Moda', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('TO165', 'nisi', 'quam nec dui', 'Educación y Gestión del Aprendizaje', 3);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('PM165', 'mauris', 'nunc nisl duis', 'Arquitectura', 3);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('TZ102', 'ipsum', 'morbi vel lectus', 'Comunicación e Imagen Empresarial', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('ME126', 'vitae', 'volutpat eleifend donec', 'Comunicación y Publicidad', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('EX122', 'elit', 'proin risus', 'Administración y Marketing', 6);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('JX189', 'fringilla', 'mi sit amet', 'Contabilidad y Administración', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('AG155', 'leo', 'metus sapien', 'Arquitectura', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('ZI185', 'augue', 'feugiat non pretium', 'Educación y Gestión del Aprendizaje', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('IE111', 'elementum', 'interdum', 'Ingeniería Civil', 6);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('DR100', 'quam', 'nisi volutpat eleifend', 'Ingeniería Ambiental', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('VH106', 'vehicula', 'ipsum', 'Administración y Negocios del Deporte', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('FO191', 'est', 'faucibus orci', 'Artes Escénicas', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('JR169', 'ipsum', 'vel est', 'Ingeniería Electrónica', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('VJ166', 'neque', 'quisque', 'Administración y Gerencia del Emprendimiento', 6);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('VF129', 'morbi', 'diam neque vestibulum', 'Administración y Marketing', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('WI194', 'cubilia', 'consequat', 'Administración y Finanzas', 3);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('LP190', 'rhoncus', 'integer', 'Economía y Finanzas', 4);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('GM107', 'odio', 'erat', 'Educación y Gestión del Aprendizaje', 3);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('LH116', 'condimentum', 'cursus vestibulum', 'Ingeniería Electrónica', 3);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('DV147', 'velit', 'morbi porttitor lorem', 'Gastronomía y Gestión Culinaria', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('HD195', 'consequat', 'bibendum', 'Administración y Gerencia del Emprendimiento', 6);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('EA177', 'ultrices', 'consequat in consequat', 'Contabilidad y Administración', 6);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('AZ139', 'volutpat', 'aliquam non mauris', 'Administración y Negocios del Deporte', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('QJ168', 'non', 'vel enim', 'Ingeniería Ambiental', 4);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('GV115', 'quis', 'pellentesque volutpat', 'Administración y Recursos Humanos', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('CP155', 'erat', 'lectus', 'Administración y Recursos Humanos', 5);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('HP164', 'morbi', 'aenean auctor gravida', 'Artes Escénicas', 2);
insert into curso (codigo, nombre, descripcion, carrera, creditaje) values ('ST182', 'sapien', 'ipsum praesent', 'Arquitectura', 6);
